import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;



/**
 *
 * @author Ps
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginTest3
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Text2 = new javax.swing.JPasswordField();
        Text1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Seller", "Admin" }));

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Text2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        Text1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel9.setText("Login");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Log in as:");

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Read email and password in BuyerAccouont if select Buyer
        String email = Text1.getText();
        String password = Text2.getText();
        String a;
        boolean b = false;
        BufferedReader reader;
        
        // If user select login as buyer, it will read BuyerAccount text file
        if (jComboBox.getSelectedItem().toString().equals("Buyer")) 
        {            
            try 
            {   
                reader = new BufferedReader(new FileReader("BuyerAccount.txt"));
                
                try 
                {
                    
                    while((a = reader.readLine()) != null) 
                    {
                        String[] readaccount = a.split("\t");
                        if (readaccount[0].equals(email) && readaccount[2].equals(password)) 
                        {
                            User buyer = new User();

                            try 
                            {                                
                                buyer.Email = readaccount[0];
                                buyer.Name = readaccount[1];
                                buyer.Password = readaccount[2];  
                                buyer.ContactNo = readaccount[3];
                                buyer.Address = readaccount[4];
                            } 
                            catch (Exception e) 
                            {
                                System.out.println(e);
                            }

                            SystemMainClass.currentUser = buyer;
                            b = true;
                        }
                    }
                    if (b == true) 
                    {
                        new BuyerMenu().setVisible(true);
                        this.dispose();            
                    } 
                    else 
                    {   
                        JOptionPane.showMessageDialog(this,"Incorrect email or password");
                    }
                } 
                catch (IOException e) 
                {
                    System.out.println(e);
                }
            } 
            catch (FileNotFoundException e) 
            {
                System.out.println(e);
            }
        }
        // If user select login as buyer, it will read SellerAccount text file    
        else if (jComboBox.getSelectedItem().toString().equals("Seller")) 
        {            
            try 
            {   
                reader = new BufferedReader(new FileReader("SellerAccount.txt"));
                
                try 
                {
                    
                    while((a = reader.readLine()) != null) 
                    {
                        String[] readaccount = a.split("\t");
                        if (readaccount[0].equals(email) && readaccount[2].equals(password)) 
                        {
                            User seller = new User();

                            try 
                            {                                
                                seller.Email = readaccount[0];
                                seller.Name = readaccount[1];
                                seller.Password = readaccount[2];  
                                seller.ContactNo = readaccount[3];
                                seller.Address = readaccount[4];
                                
                            } 
                            catch (Exception e) 
                            {
                                System.out.println(e);
                            }

                            SystemMainClass.currentUser = seller;
                            b = true;
                        }
                    }
                    if (b == true) 
                    {
                        new SellerMenu().setVisible(true);
                        this.dispose();            
                    } 
                    else 
                    {   
                        JOptionPane.showMessageDialog(this,"Incorrect email or password");
                    }
                } 
                catch (IOException e) 
                {
                    System.out.println(e);
                }
            } 
            catch (FileNotFoundException e) 
            {
                System.out.println(e);
            }           
        }
        // If user select login as buyer, it will read AdminAccount text file
        else if (jComboBox.getSelectedItem().toString().equals("Admin")) 
        {            
            try 
            {   
                reader = new BufferedReader(new FileReader("AdminAccount.txt"));
                
                try 
                {
                    
                    while((a = reader.readLine()) != null) 
                    {
                        String[] readaccount = a.split("\t");
                        if (readaccount[0].equals(email) && readaccount[1].equals(password)) 
                        {
                            User Admin = new User();

                            try 
                            {                                
                                
                                Admin.Name = readaccount[0];
                                Admin.Password = readaccount[1];  
                                                           
                            } 
                            catch (Exception e) 
                            {
                                System.out.println(e);
                            }

                            SystemMainClass.currentUser = Admin;
                            b = true;
                        }
                    }
                    if (b == true) 
                    {
                        new AdminMenu().setVisible(true);
                        this.dispose();            
                    } 
                    else 
                    {   
                        JOptionPane.showMessageDialog(this,"Incorrect email or password");
                    }
                } 
                catch (IOException e) 
                {
                    System.out.println(e);
                }
            } 
            catch (FileNotFoundException e) 
            {
                System.out.println(e);
            }           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new GuestViewItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Text1;
    private javax.swing.JPasswordField Text2;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
