
import javax.swing.JOptionPane;
import java.io.*;

public class Registration extends javax.swing.JFrame {

   
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        EmailText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ConfirmPassText = new javax.swing.JPasswordField();
        ContactNoText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddressText = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel9.setText("Registration");

        jComboBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Seller" }));
        jComboBox.setBorder(null);

        EmailText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Sign up as: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Name:");

        NameText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        PasswordText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Password:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Confirm Password:");

        ConfirmPassText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        ContactNoText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        AddressText.setColumns(20);
        AddressText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        AddressText.setLineWrap(true);
        AddressText.setRows(5);
        AddressText.setWrapStyleWord(true);
        AddressText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(AddressText);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Contact No.:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Postal Address:");

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ConfirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7))
                    .addComponent(ContactNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String Email, Name,Password,ContactNo,Address,ConPassword;
        
        //If user select buyer, user details will store in BuyerAccount text file
        
        if (jComboBox.getSelectedItem().toString().equals("Buyer"))
        {

            User buyer = new User();

            Email = buyer.Email;
            Name = buyer.Name;
            Password = buyer.Password;
            ContactNo = buyer.ContactNo;
            Address = buyer.Address;

            Email = EmailText.getText();
            Name = NameText.getText();
            Password = PasswordText.getText();
            ConPassword = ConfirmPassText.getText();
            ContactNo = ContactNoText.getText();
            Address = AddressText.getText();
            
            
            if (!(Email.matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")))
            {
                JOptionPane.showMessageDialog(this,"Please enter valid email");
            }

            else if (Name.length() <= 0 || Password.length() <= 0)
            {
                JOptionPane.showMessageDialog(this,"Name and password cannot be empty");
            }

            else if (Name.length() <= 4 || Name.length() >= 31)
            {
                JOptionPane.showMessageDialog(this,"Please enter at least 5-30 character only in name field");
            }

            else if (Password.length() <= 5 || Password.length() >=11 )
            {
                JOptionPane.showMessageDialog(this,"Please enter at least 6-10 character only in password field");
            }

            else if (!(Name.matches("[a-zA-Z ]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet only in Name field");

            }

            else if (!(Password.matches("[0-9a-zA-Z]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet or digit in Password field only");
            }

            else if (!(ConPassword.equals(Password)))
            {
                JOptionPane.showMessageDialog(this,"Password did not match");
            }

            else if (ContactNo == null || !(ContactNo.matches("\\d{10}|\\d{11}")))
            {
                JOptionPane.showMessageDialog(this,"Please enter Contact Number with 10 or 11 digits only");
            }

            else if (Address == null || !(Address.matches("[a-zA-Z0-9/ ]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet, digit or slash punctuation in Address field only");
            }
            
            else
            {                            
                File file = new File ("BuyerAccount.txt");
                try (BufferedWriter writer = new BufferedWriter (new FileWriter(file,true)))
                {                   
                    writer.write(Email+"\t"+Name+"\t"+Password+"\t"+ContactNo+"\t"+Address+ "\t" + "0" +System.lineSeparator());                    
                }
                catch (IOException e)
                {
                    System.out.println("Error is" + e);
                }

                JOptionPane.showMessageDialog(this,"Sign Up Successful");
                new Login().setVisible(true);
                this.dispose();
                
            }

        //If user select seller, user details will store in SellerAccount text file
        }
        else if (jComboBox.getSelectedItem().toString().equals("Seller"))
        {

            User seller = new User();

            Email = seller.Email;
            Name = seller.Name;
            Password = seller.Password;
            ContactNo = seller.ContactNo;
            Address = seller.Address;

            Email = EmailText.getText();
            Name = NameText.getText();
            Password = PasswordText.getText();
            ConPassword = ConfirmPassText.getText();
            ContactNo = ContactNoText.getText();
            Address = AddressText.getText();

            if (!(Email.matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")))
            {
                JOptionPane.showMessageDialog(this,"Please enter valid email");
            }

            else if (Name.length() <= 0 || Password.length() <= 0)
            {
                JOptionPane.showMessageDialog(this,"Name and password cannot be empty");
            }

            else if (Name.length() <= 4 || Name.length() >= 31)
            {
                JOptionPane.showMessageDialog(this,"Please enter at least 5-30 character only in name field");
            }

            else if (Password.length() <= 5 || Password.length() >=11 )
            {
                JOptionPane.showMessageDialog(this,"Please enter at least 6-10 character only in password field");
            }

            else if (!(Name.matches("[a-zA-Z ]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet only in Name field");
                EmailText.requestFocus();
            }

            else if (!(Password.matches("[0-9a-zA-Z]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet or digit in Password field only");
            }

            else if (!(ConPassword.equals(Password)))
            {
                JOptionPane.showMessageDialog(this,"Password did not match");
            }

            else if (ContactNo == null || !(ContactNo.matches("\\d{10}|\\d{11}")))
            {
                JOptionPane.showMessageDialog(this,"Please enter Contact Number with 10 or 11 digits only");
            }

            else if (Address == null || !(Address.matches("[a-zA-Z0-9/ ]+")))
            {
                JOptionPane.showMessageDialog(this,"Please enter alphabet, digit or slash punctuation in Address field only");
            }

            else
            {
                File file = new File ("SellerAccount.txt");
                try (BufferedWriter writer = new BufferedWriter (new FileWriter(file,true)))
                {                    
                    writer.write(Email+"\t"+Name+"\t"+Password+"\t"+ContactNo+"\t"+Address+ "\t" + "0" +System.lineSeparator());                   
                }
                catch (IOException e)
                {
                    System.out.println("Error is" + e);
                }

                JOptionPane.showMessageDialog(this,"Sign Up Successful");
                new Login().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        EmailText.setText("");
        NameText.setText("");
        PasswordText.setText("");
        ConfirmPassText.setText("");
        ContactNoText.setText("");
        AddressText.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       new GuestViewItems().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressText;
    private javax.swing.JPasswordField ConfirmPassText;
    private javax.swing.JTextField ContactNoText;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField NameText;
    private javax.swing.JPasswordField PasswordText;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
