import java.io.*;
import javax.swing.JOptionPane;

public class SellerAccount extends javax.swing.JFrame {

    String Email;
    double currentBal;
   
    public SellerAccount() {
        initComponents();
        Email = SystemMainClass.currentUser.Email;
        
        
        
        // read from text file and set text read in text file in textfield
        
        try 
        {
            BufferedReader reader= new BufferedReader(new FileReader("SellerAccount.txt"));
            try 
            {
                String a;
                while ((a = reader.readLine()) != null) 
                {
                    String[] read = a.split("\t");
                    if (read[0].equals(Email)) 
                    {
                        EmailText.setText(read[0]);
                        NameText.setText(read[1]); 
                        PasswordText.setText(read[2]);
                        ContactNoText.setText(read[3]);
                        AddressText.setText(read[4]);
                        currentBal = Double.parseDouble(read[5]);
                        CurrentBLabel.setText(String.valueOf(currentBal));
                    }
                    
                }
            } 
            catch (IOException e) 
            {
                System.out.println(e);
            }
        }
        catch (FileNotFoundException e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        EmailText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ContactNoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressText = new javax.swing.JTextArea();
        PasswordText = new javax.swing.JPasswordField();
        ConfirmPassText = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CurrentBLabel = new javax.swing.JLabel();
        CardNoText = new javax.swing.JTextField();
        CardNameText = new javax.swing.JTextField();
        SecurityCText = new javax.swing.JTextField();
        AddCreditButton = new javax.swing.JButton();
        AmountText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Back1Button = new javax.swing.JButton();
        CurrentBLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel9.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        EmailText.setEditable(false);
        EmailText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        NameText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        UpdateButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel4.setText("Confirm Password:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel5.setText("Contact No:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel6.setText("Postal Address:");

        ContactNoText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        AddressText.setColumns(20);
        AddressText.setLineWrap(true);
        AddressText.setRows(5);
        AddressText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(AddressText);

        PasswordText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        ConfirmPassText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel10.setText("Update");

        BackButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateButton)
                    .addComponent(BackButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update", jPanel1);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel7.setText("Current Balance:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel8.setText("Card Number:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel11.setText("Name on Card:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel12.setText("Security Code:");

        CurrentBLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        CurrentBLabel.setText("CurrentBLabel");

        CardNoText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        CardNameText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        SecurityCText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        AddCreditButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        AddCreditButton.setText("Add Credit");
        AddCreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCreditButtonActionPerformed(evt);
            }
        });

        AmountText.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel14.setText("Amount:");

        Back1Button.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        Back1Button.setText("Back");
        Back1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ButtonActionPerformed(evt);
            }
        });

        CurrentBLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        CurrentBLabel1.setText("RM");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel15.setText("Add Credit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SecurityCText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CardNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(CurrentBLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CurrentBLabel)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(AddCreditButton)
                .addGap(18, 18, 18)
                .addComponent(Back1Button, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentBLabel1)
                    .addComponent(jLabel7)
                    .addComponent(CurrentBLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CardNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SecurityCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCreditButton)
                    .addComponent(Back1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Add Credit", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
      
        String Email, Name,Password,ContactNo,Address,confirmPass;
        
        User seller = new User();

        Email = seller.Email;
        Name = seller.Name;
        Password = seller.Password;
        ContactNo = seller.ContactNo;
        Address = seller.Address;

        Email = EmailText.getText();
        Name = NameText.getText();
        Password = PasswordText.getText();
        confirmPass = ConfirmPassText.getText();
        ContactNo = ContactNoText.getText();
        Address = AddressText.getText();
             
        
        String WriteText = "";
        String a;   
                
             

        if (Name.length() <= 0 || Password.length() <= 0)
        {
            JOptionPane.showMessageDialog(this,"Name and password cannot be empty");
        }

        else if (Name.length() <= 4 || Name.length() >= 31)
        {
            JOptionPane.showMessageDialog(this,"Please enter at least 5-30 character only in name field");
        }

        else if (Password.length() <= 5 || Password.length() >=11 )
        {
            JOptionPane.showMessageDialog(this,"Please enter at least 6-10 character only in password field");
        }

        else if (!(Name.matches("[a-zA-Z ]+")))
        {
            JOptionPane.showMessageDialog(this,"Please enter alphabet only in Name field");
        }
        else if (!(Password.matches("[0-9a-zA-Z]+")))
        {
            JOptionPane.showMessageDialog(this,"Please enter alphabet or digit in Password field only");
        }
        else if (confirmPass.length()>=1 && !(confirmPass.equals(Password)))
        {
            JOptionPane.showMessageDialog(this,"Password does not match");
        }

        else if (ContactNo == null || !(ContactNo.matches("\\d{10}|\\d{11}")))
        {
            JOptionPane.showMessageDialog(this,"Please enter Contact Number with 10 or 11 digits only");
        }

        else if (Address == null || !(Address.matches("[a-zA-Z0-9/ ]+")))
        {
            JOptionPane.showMessageDialog(this,"Please enter alphabet, digit or slash punctuation in Address field only");
        }

        else
        {
            try 
            {
                BufferedReader reader = new BufferedReader(new FileReader("SellerAccount.txt"));

                try 
                {                              
                    while ((a = reader.readLine()) != null) 
                    {   
                        String[] read = a.split("\t");
                        if (read[0].equals(Email)) 
                        {   
                            read[0] = EmailText.getText();                      
                            read[1] = NameText.getText();
                            read[2] = PasswordText.getText();
                            read[3] = ContactNoText.getText();
                            read[4] = AddressText.getText();

                            WriteText += read[0] + "\t" + read[1] + "\t" + read[2] + "\t" + read[3] + "\t" +  read[4] + "\t" + read[5] + System.lineSeparator();
                            ConfirmPassText.setText("");                      
                        }                      
                        else 
                        {
                            WriteText += a +System.lineSeparator();
                        }
                    }
                }
                catch (IOException e)
                {
                    System.out.println(e);
                }
            }
            catch (FileNotFoundException e)
            {
                System.out.println(e);
            }

            try(BufferedWriter writer = new BufferedWriter(new FileWriter("SellerAccount.txt")))
            {
                writer.write(WriteText);
                JOptionPane.showMessageDialog(this, "Update Successfully!");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
       
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new SellerMenu().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddCreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCreditButtonActionPerformed
        // TODO add your handling code here:
        
        double Amount, newBal;
        String CardNo, NameonCard, SecurityCode,a;
        
        
        CardNo = CardNoText.getText();
        NameonCard = CardNameText.getText();
        SecurityCode = SecurityCText.getText();
        
        String WriteText ="";
        
        
       
        BufferedReader reader;
        
        if(!(AmountText.getText().matches("[0-9]+")) || AmountText.getText() == null)
        {
            JOptionPane.showMessageDialog(this,"Enter number in Amount Field only");
        }
        else if(!(CardNo.matches("\\d{16}")) || CardNo == null)
        {
            JOptionPane.showMessageDialog(this,"Please enter valid Credit Card or Debit Card");
        }
        else if(!(NameonCard.matches(("[a-zA-Z ]+"))) || NameonCard == null)
        {
            JOptionPane.showMessageDialog(this,"Please enter valid Name on Card");
        }
        else if(!(SecurityCode.matches("\\d{3}")) || SecurityCode == null)
        {
            JOptionPane.showMessageDialog(this,"Please enter valid Security Code");
        }
        else 
        {
            try
            {   
                Amount = Double.parseDouble(AmountText.getText());
                newBal = currentBal + Amount;
                currentBal = newBal;
                
                reader = new BufferedReader(new FileReader("SellerAccount.txt"));
                while ((a = reader.readLine()) != null) 
                    {                        
                        String[] read = a.split("\t");
                        if (read[0].equals(Email)) 
                        {
                            read[5] = String.valueOf(newBal);
                            CurrentBLabel.setText(String.valueOf(newBal));
                            WriteText += read[0] +"\t"+ read[1] +"\t"+ read[2] +"\t"+ read[3] +"\t"+ read[4] +"\t"+ read[5] +System.lineSeparator();
                            JOptionPane.showMessageDialog(this, "Credit has added into account!");
                        }
                        else 
                        {
                            WriteText += a + System.lineSeparator();
                        }
                    }
                }
                catch (IOException | NumberFormatException e)
                {
                    System.out.println(e);
                }
                       
            try(BufferedWriter writer = new BufferedWriter(new FileWriter("SellerAccount.txt")))
            {
                writer.write(WriteText);
            }
            catch(Exception e)
            {
                 System.out.println(e);
            }
            AmountText.setText("");
            CardNoText.setText("");
            CardNameText.setText("");
            SecurityCText.setText("");
        }
    }//GEN-LAST:event_AddCreditButtonActionPerformed

    private void Back1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ButtonActionPerformed
        // TODO add your handling code here:
        new SellerMenu().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_Back1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCreditButton;
    private javax.swing.JTextArea AddressText;
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton Back1Button;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CardNameText;
    private javax.swing.JTextField CardNoText;
    private javax.swing.JPasswordField ConfirmPassText;
    private javax.swing.JTextField ContactNoText;
    private javax.swing.JLabel CurrentBLabel;
    private javax.swing.JLabel CurrentBLabel1;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField NameText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField SecurityCText;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
